spring:
  application:
    name: jpa-mappings

  datasource:
    url: jdbc:mysql://localhost:3306/data-jpa
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create